server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: fuel-pass-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/fuel-pass-dev
    username: postgres
    password: Qwer@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: admin123

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 900000 # 15 minutes in milliseconds
  refresh:
    expiration: 604800000 # 7 days in milliseconds

# Logging
logging:
  level:
    com.fuelpass: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always